// @ts-check

"use strict";

import * as shared from "./custom-shared.mjs";

export const names = ["AM022", "header-anchor-collision"];
export const description = "Heading anchor has collision";
export const tags = ["headings", "headers"];

export function function_(params, onError) {
    var anchors = Object.create(null);
    var collision = Object.create(null);

    /* loop one to get list of all anchors */
    shared.forEachHeading(params, function forHeading(token, content) {
        var linenumber = (Array.isArray(token.map) ? (token.map[0]+1) : ((token.lineNumber||1)));
        var headingtitle = (params.lines[linenumber-1] || "").replace(/^[#]+ /, '').replace(/[\s]*\{\#.*?\}[\s]*$/, '');
        var hasanchor = ((params.lines[linenumber-1] || "").search(/\{#.*?\}[\s]*$/) >= 0);
        var anchorid = (params.lines[linenumber-1] || "").replace(/^.*?[\s]*\{\#(.*?)\}[\s]*$/, '$1');
        var sluganchorid = '';
        var key = '';

        headingtitle = headingtitle.replace(/\[!DNL (.*?)]/, "$1");
        headingtitle = headingtitle.replace(/\[!UICONTROL (.*?)]/, "$1");

        if (!hasanchor) {
            anchorid = "";
            sluganchorid = shared.slugify(headingtitle);
            if (!(sluganchorid in collision)) {
                collision[sluganchorid] = 1;
            }
            if (sluganchorid in anchors) {
                collision[sluganchorid] = collision[sluganchorid] + 1;
                sluganchorid = sluganchorid + '-' + collision[sluganchorid].toString();
            }
        }

        key = anchorid ? anchorid : sluganchorid;

        if (!(key in anchors)) {
            anchors[key] = [];
        }
        anchors[key].push({
            anchorid: anchorid,
            slug: sluganchorid,
            linenumber: linenumber
        });
    });

    for (const [key, value] of Object.entries(anchors)) {
        if (value.length > 1) {
            for (const [_, value2] of Object.entries(value)) {
                var anchortype = value2.slug ? " (autogenerated) " : "";
                shared.addError(
                    onError,
                    value2.linenumber,
                    null,
                    "Duplicate anchor " + anchortype + "'" + key + "'"
                );
            }
        }
    }
}

export default {
    names,
    description,
    tags,
    function: function_,
};